# Generated by Django 4.1.5 on 2023-01-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.watchlist'),
        ),
    ]
