# Generated by Django 4.1.5 on 2023-01-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='biggest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
